version: "3.8"
services:
  java-app:
    build:
      context: .
    container_name: "LIBMANAGEMENT"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/library
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - "8080"
    depends_on:
      - mysql_db
    restart: always
    networks:
      - libnetwork

  mysql_db:
    image: mysql:latest
    container_name: "mysql"
    restart: always
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=library
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - libnetwork

networks:
  libnetwork:
    driver: bridge
